<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Need)</span></div>

## 1 User defined functions

### 1.1 Named functions that return

In [2]:
def greeting(name):
    if name == "Batman":
        return "Hello Batman! Nice to meet you."
    else:
        return f'Hello {name}!'
    
greeting("Superman")

'Hello Superman!'

In [3]:
greeting("Batman")

'Hello Batman! Nice to meet you.'

In [4]:
greeting(name="Batman")

'Hello Batman! Nice to meet you.'

In [8]:
def basic_stats(numbers):
    np_numbers = np.array(numbers)
    return np_numbers.min(), np_numbers.max(), np_numbers.mean()

basic_stats([1, 2, 3, 4, 5])

(1, 5, 3.0)

### 1.2 Named functions that don’t return

### 1.3 Anonymous functions

In [9]:
# lambda suitable for small piece of function that will be run once in a while

short_function = lambda name: f'Hello {name}!'

short_function("Superman")

'Hello Superman!'

In [10]:
numbers=[[9, 0, 10],
         [8, 1, 11],
         [7, 2, 12],
         [6, 3, 13],
         [5, 4, 14],
         [4, 5, 15],
         [3, 6, 16],
         [2, 7, 17],
         [1, 8, 18],
         [0, 9, 19]]

sorted(numbers)                         # Sort by comparing the default key 
                                        # (i.e. the 1st element) 

[[0, 9, 19],
 [1, 8, 18],
 [2, 7, 17],
 [3, 6, 16],
 [4, 5, 15],
 [5, 4, 14],
 [6, 3, 13],
 [7, 2, 12],
 [8, 1, 11],
 [9, 0, 10]]

In [13]:
help(sorted)

Help on built-in function sorted in module builtins:

sorted(iterable, /, *, key=None, reverse=False)
    Return a new list containing all items from the iterable in ascending order.
    
    A custom key function can be supplied to customize the sort order, and the
    reverse flag can be set to request the result in descending order.



In [14]:
sorted(numbers, key = lambda x: x[1])

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

In [15]:
sorted(numbers, key = lambda x: sum(x))

[[9, 0, 10],
 [8, 1, 11],
 [7, 2, 12],
 [6, 3, 13],
 [5, 4, 14],
 [4, 5, 15],
 [3, 6, 16],
 [2, 7, 17],
 [1, 8, 18],
 [0, 9, 19]]

### 1.4 Optional arguments

In [17]:
def greeting(name='no one'):   # default value
    if name == 'Batman':
        return 'Hello Batman! So, nice to meet you!'
    else:
        return f'Hello {name}!'
    
greeting()

'Hello no one!'

In [20]:
print('i', 'am', 'batman', sep = '---')

i---am---batman


## 2 The importance of functions?

### 2.1 An argument for functions

### 2.2 A word of caution

In [ ]:

# Your code here


## Exercise 1 :  Do you know why?

'return' ends the execution of the code under 'if', and executes the return value

## Exercise 2 :  Calculator functions

In [1]:
import numpy as np

In [8]:
def add(x,y):
    return x + y

In [9]:
def subtract(x,y):
    return x - y

In [10]:
def multiply(x,y):
    return x*y

In [2]:
def divide(x,y):
    if 0 in y:
        exit()
    return x/y

In [3]:
x= np.array([36, 34, 44, 76, 27])
y= np.array([0, 66, 56, 24, 73])

In [13]:
add(x,y)

array([ 36, 100, 100, 100, 100])

In [14]:
subtract(x,y)

array([ 36, -32, -12,  52, -46])

In [15]:
multiply(x,y)

array([   0, 2244, 2464, 1824, 1971])

In [4]:
divide(x,y)

C:\Users\punen\AppData\Local\Temp\ipykernel_19228\2005831635.py:4: RuntimeWarning: divide by zero encountered in divide
  return x/y


array([       inf, 0.51515152, 0.78571429, 3.16666667, 0.36986301])

## Exercise 3 :  max_info() with NumPy

In [24]:
def max_info(numbers):
    numbers_array = np.array(numbers)
    return f'Maximum value = {np.max(numbers_array)}, index = {np.argmax(numbers_array)}'

In [25]:
numbers = [40, 27, 83, 44, 74, 51, 76, 77, 10, 49]

In [26]:
max_info(numbers)

'Maximum value = 83, index = 2'