<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Functions (Nice)</span></div>

## 1 Other things you can do with functions

### 1.1 Modularise and reuse

In [ ]:

# Your code here


## 2 *args & **kwarg

### 2.1 *args

In [1]:
def multiply(x, y):
    return x * y

numbers = [1, 2]
multiply(*numbers)

2

In [3]:
def multiply(*args):
    result = 1
    for number in args:
        result *= number
    
    return result

multiply(1, 2, 3, 4, 5)

120

### 2.2 **kwargs

In [4]:
def multiply(x, y, z):
    return x * y * z

numbers = {'x': 1, 'y': 2, 'z': 3}
multiply(**numbers)

6

In [5]:
def multiply(x, y, z):
    return x * y * z

numbers = {'y': 2, 'z': 3}
multiply(1, **numbers)

6

In [6]:
def add_powers(numbers, power):
    result = 1
    for number in numbers:
        result *= number**power

    return result

kwargs = {'numbers': [1, 2, 3], 'power': 2}
add_powers(**kwargs)

36

In [7]:
def add_powers(**kwargs):
    numbers = kwargs['numbers']
    power = kwargs['power']
    
    result = 1
    for number in numbers:
        result *= number**power
        
    
    return result

add_powers(numbers=[1, 2, 3], power = 2)

36

### 2.3 Passing variable to functions

For 'immutable' variables e.g. int, float, string, what happens inside the function does not change the variable outside.

For 'mutable' variables e.g. list, dict, array, what happens inside the function does change the variable outside.

In [8]:
def do_something(inside_number, inside_array, inside_list):
    print('Doing something!')
    inside_number *= 2
    inside_array *= 2
    inside_list *= 2

outside_number=10
outside_array=np.array([10])
outside_list=[10]

print(
    f"BEFORE\t--->\tNumber: {outside_number}, Array: {outside_array}, List: {outside_list}")

BEFORE	--->	Number: 10, Array: [10], List: [10]


In [9]:
do_something(outside_number, outside_list, outside_array)

Doing something!


In [10]:
print(
    f"AFTER\t--->\tNumber: {outside_number}, Array: {outside_array}, List: {outside_list}")

AFTER	--->	Number: 10, Array: [20], List: [10, 10]


## 3 There is more to exceptions

### 3.1 A list of exceptions

In [ ]:

# Your code here


### 3.2 Handling specific exceptions

In [11]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except ValueError:
    print(f"Oh oh! I cannot square {number}!")

Give me a number and I will calculate its square.two
Oh oh! I cannot square two!


### 3.3 try also has an else

In [12]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except ValueError:
    print(f"Oh oh! I cannot square {number}!")
else:
    print('Yeah! Things ran without a problem!')

Give me a number and I will calculate its square.2
The square of 2 is 4!
Yeah! Things ran without a problem!


In [13]:
try:
    number=input("Give me a number and I will calculate its square.")
    square=int(number)**2
    print(f'The square of {number} is {square}!')
except ValueError:
    print(f"Oh oh! I cannot square {number}!")
else:
    print('Yeah! Things ran without a problem!')

Give me a number and I will calculate its square.two
Oh oh! I cannot square two!


## Explore 1 :  Modularise

In [15]:
import my_math
my_math.add(1, 2)

3

In [16]:
from my_math import add as my_add
my_add(1, 2)

3

## Explore 2 :  Angles and trig functions

In [31]:
def my_trig_function(*args, **kwargs):
    result = []
    functions = kwargs['functions']
    mode = kwargs.get('mode','degrees')
    
    if mode == 'degrees':
        args = [np.deg2rad(args) for i in args]

    for i, angle in enumerate(args):
        trig_function_value = functions[i](angle)
        result.append([angle, trig_function_value])
    
    return(result)

my_trig_function(90, 180, 45,
                functions = [np.sin, np.cos, np.tan],
                mode = 'degrees')

[[array([1.57079633, 3.14159265, 0.78539816]),
  array([1.00000000e+00, 1.22464680e-16, 7.07106781e-01])],
 [array([1.57079633, 3.14159265, 0.78539816]),
  array([ 6.12323400e-17, -1.00000000e+00,  7.07106781e-01])],
 [array([1.57079633, 3.14159265, 0.78539816]),
  array([ 1.63312394e+16, -1.22464680e-16,  1.00000000e+00])]]

In [32]:
def my_trig_function(*args, **kwargs):
    result = []
    functions = kwargs['functions']
    mode = kwargs

    for i, angle in enumerate(args):
        trig_function_value = functions[i](angle)
        result.append([angle, trig_function_value])
    
    return(result)

my_trig_function(90, 180, 45,
                functions = [np.sin, np.cos, np.tan])

[[90, 0.8939966636005579],
 [180, -0.5984600690578581],
 [45, 1.6197751905438615]]