<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good)</span></div>

## 1 Subsetting: Indexing and Slicing

### 1.1 Indexing & Slicing 1D (Lists & Arrays)

In [2]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]

np_array = np.array(py_list)

x = np_array

In [3]:
x[0]

'a1'

In [4]:
x[0:3]

array(['a1', 'b2', 'c3'], dtype='<U3')

In [5]:
x[1:6]

array(['b2', 'c3', 'd4', 'e5', 'f6'], dtype='<U3')

In [6]:
x[1:6:2]

array(['b2', 'd4', 'f6'], dtype='<U3')

In [7]:
x[1:5]

array(['b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [8]:
x[:5]

array(['a1', 'b2', 'c3', 'd4', 'e5'], dtype='<U3')

In [9]:
x[::-1]

array(['j10', 'i9', 'h8', 'g7', 'f6', 'e5', 'd4', 'c3', 'b2', 'a1'],
      dtype='<U3')

In [10]:
x[5:2:-1]

array(['f6', 'e5', 'd4'], dtype='<U3')

### 1.2 Subsetting by masking (Arrays only)

In [11]:
np_array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
my_mask = np_array > 3
print(my_mask)

[False False False  True  True  True  True  True  True  True]


In [12]:
np_array[my_mask]

array([ 4,  5,  6,  7,  8,  9, 10])

In [13]:
np_array[np_array > 3]

array([ 4,  5,  6,  7,  8,  9, 10])

In [14]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [16]:
np_array[(np_array < 3) | (np_array > 8)]

array([ 1,  2,  9, 10])

### 1.3 Indexing & Slicing 2D Lists

In [17]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

In [18]:
py_list_2d[3]

[4, 'D']

In [19]:
py_list_2d[3][0]

4

In [22]:
py_list_2d[:3][0]     # gives the first of the list from py_list_2d[:3]

[1, 'A']

### 1.4 Indexing & Slicing 2D Arrays

In [23]:
np_array_2d = np.array([[1, "A"], [2, "B"], [3, "C"], [4, "D"],
                        [5, "E"], [6, "F"], [7, "G"], [8, "H"],
                        [9, "I"], [10, "J"]])

In [24]:
np_array_2d[3]

array(['4', 'D'], dtype='<U11')

In [25]:
np_array_2d[3, 0]

'4'

In [26]:
np_array_2d[:3, 0]

array(['1', '2', '3'], dtype='<U11')

In [27]:
np_array_2d[3:6, 0]


array(['4', '5', '6'], dtype='<U11')

In [28]:
np_array_2d[:, 0]


array(['1', '2', '3', '4', '5', '6', '7', '8', '9', '10'], dtype='<U11')

### 1.5 Growing lists

In [31]:
x = [1]*10
print(x)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


In [38]:
x = [1]
x += [2, 3, 4]
x

[1, 2, 3, 4]

In [39]:
x = [5, 6, 7] + x
x

[5, 6, 7, 1, 2, 3, 4]

In [43]:
x = [1]
x.append(2)
x.append(3)
x.append(4)
x

[1, 2, 3, 4]

## 2 Some loose ends

### 2.1 Tuples

Tuples cannot be changed after creation

In [44]:
a = (1, 2, 3)

In [45]:
print(a[0])

1


In [49]:
a[0] = -1

TypeError: 'tuple' object does not support item assignment

In [47]:
a[0] += [10]

TypeError: unsupported operand type(s) for +=: 'int' and 'list'

### 2.2 Be VERY careful when copying

In [50]:
x=[1, 2, 3]
y=x.copy()
z=x.copy()

## Exercise 1 :  Total recall?

| Term       | Brief Description                                      |
|------------|--------------------------------------------------------|
| Subsetting | 'select'                                               |
| Indexing   | selecting an element                                   |
| Slicing    | selecting a range of elements                          |
| Masking    | *only show certain elements that fulfil the condition* |

## Exercise 2 :  Show me the ‘odd’ letters

In [8]:
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])

In [9]:
first_elements = np_array_2d[:, 0]
first_elements

array(['1', '3', '2', '4', '5', '7', '6', '8', '10', '9'], dtype='<U11')

In [10]:
int_first_elements = first_elements.astype(int)
int_first_elements

array([ 1,  3,  2,  4,  5,  7,  6,  8, 10,  9])

In [11]:
remainder = int_first_elements % 2

In [12]:
odd_locations = np_array_2d[(remainder == 1)]
odd_locations

array([['1', 'A'],
       ['3', 'C'],
       ['5', 'E'],
       ['7', 'G'],
       ['9', 'I']], dtype='<U11')

In [13]:
odd_second_elements = odd_locations[:, 1]
odd_second_elements

array(['A', 'C', 'E', 'G', 'I'], dtype='<U11')