<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Need)</span></div>

## 1 Lists, Arrays & Dictionaries

### 1.1 Let’s compare

In [11]:
# Python list

py_super_names = ["Black Widow", "Iron Man", "Doctor Strange"]

In [12]:
# Numpy array

np_super_names = np.array(["Black Widow", "Iron Man", "Doctor Strange"])

In [13]:
# Dictionary

superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

### 1.2 Accessing data from a list (or array)

In [14]:
super_names = ["Black Widow", "Iron Man", "Doctor Strange"]

print(super_names[0])

Black Widow


In [15]:
real_names = ["Natasha Romanoff", "Tony Stark", "Stephen Strange"]

print(real_names[2])

Stephen Strange


In [16]:
print(real_names[-1])

Stephen Strange


### 1.3 Accessing data from a dictionary

In [18]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

print(superhero_info["Natasha Romanoff"])

Black Widow


In [19]:
superhero_info.keys()

dict_keys(['Natasha Romanoff', 'Tony Stark', 'Stephen Strange'])

In [20]:
superhero_info.values()

dict_values(['Black Widow', 'Iron Man', 'Doctor Strange'])

### 1.4 Higher dimensional lists

In [22]:
py_superhero_info = [['Natasha Romanoff', 'Black Widow'],
                     ['Tony Stark', 'Iron Man'],
                     ['Stephen Strange', 'Doctor Strange']]

print(py_superhero_info[0])

['Natasha Romanoff', 'Black Widow']


In [24]:
print(py_superhero_info[1])

['Tony Stark', 'Iron Man']


## 2 Lists vs. Arrays

### 2.1 Size

In [26]:
py_list_2d = [[1, "A"], [2, "B"], [3, "C"], [4, "D"],
              [5, "E"], [6, "F"], [7, "G"], [8, "H"],
              [9, "I"], [10, "J"]]

np_array_2d = np.array(py_list_2d)

In [27]:
len(py_list_2d)

10

In [28]:
len(np_array_2d)

10

In [29]:
np_array_2d.shape

(10, 2)

### 2.2 Arrays are fussy about type

In [31]:
py_list = [1, 1.5, 'A']
np.array(py_list)      # Numpy arrays tolerate only a single type

array(['1', '1.5', 'A'], dtype='<U32')

### 2.3 Adding a number

In [32]:
py_list = [1, 2, 3, 4, 5]

In [33]:
py_list + 10

TypeError: can only concatenate list (not "int") to list

In [34]:
np_array = np.array(py_list)

In [35]:
np_array + 10

array([11, 12, 13, 14, 15])

### 2.4 Adding another list

In [37]:
py_list_1 = [1, 2, 3, 4, 5]
py_list_2 = [10, 20, 30, 40, 50]

np_array_1 = np.array(py_list_1)
np_array_2 = np.array(py_list_2)

In [39]:
py_list_1 + py_list_2   # Appends the list

[1, 2, 3, 4, 5, 10, 20, 30, 40, 50]

In [41]:
np_array_1 + np_array_2   # Adds the values

array([11, 22, 33, 44, 55])

### 2.5 Multiplying by a Number

In [42]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list) 

In [46]:
py_list*2 # Multiplies the list

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [45]:
np_array*2  # Multiplies the values by the number

array([ 2,  4,  6,  8, 10])

### 2.6 Squaring

In [48]:
py_list**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [49]:
np_array**2

array([ 1,  4,  9, 16, 25])

### 2.7 Asking questions

In [50]:
py_list == 3

False

In [51]:
np_array == 3

array([False, False,  True, False, False])

In [52]:
np_array > 3

array([False, False, False,  True,  True])

### 2.8 Mathematics

In [53]:
sum(py_list)

15

In [54]:
max(py_list)

5

In [55]:
min(py_list)

1

In [56]:
np_array.sum()

15

In [57]:
np_array.mean()

3.0

In [58]:
np_array.min()

1

In [59]:
np_array.max()

5

## Exercise 1 :  Total recall?

1. 2 similarities between lists and arrays
- Order matters
- Can access the elements using indexes (starting from 0)

2. 2 differences between lists and arrays
- When using +, it extends the list but adds the elements of the array
- When using \*, it multiplies the list but multiples the elements of the array by that number

3. What is a dictionary?
*A dictionary stores elements using a key and the associated value with each key is separated by a :*

## Exercise 2 :  Index me

In [67]:
py_list = ["a1", "b2", "c3", "d4", "e5", "f6", "g7", "h8", "i9", "j10"]
print(py_list[0])                  
print(py_list[2])                   
print(py_list[4])                   
print(py_list[6])                    
print(py_list[8]) 

a1
c3
e5
g7
i9


## Exercise 3 :  Capitalise Heros

In [71]:
superhero_info = {"Natasha Romanoff": "Black Widow",
                  "Tony Stark": "Iron Man",
                  "Stephen Strange": "Doctor Strange"
                  }

superhero_info['Tony Stark'] = superhero_info['Tony Stark'].upper()
superhero_info['Natasha Romanoff'] = superhero_info['Natasha Romanoff'].upper()
superhero_info['Stephen Strange'] = superhero_info['Stephen Strange'].upper()

In [72]:
superhero_info

{'Natasha Romanoff': 'BLACK WIDOW',
 'Tony Stark': 'IRON MAN',
 'Stephen Strange': 'DOCTOR STRANGE'}

## Exercise 4 :  How many ones

In [73]:
numbers=[45, 60, 1, 30, 96, 1, 96, 57, 16, 1,
        99, 62, 86, 43, 42, 60, 59, 1, 1, 35,
        83, 47, 34, 28, 68, 23, 22, 92, 1, 79,
        1, 29, 94, 72, 46, 47, 1, 74, 32, 20,
        8, 37, 35, 1, 89, 29, 86, 19, 43, 61] 

np_array = np.array(numbers)

In [74]:
np_array == 1

array([False, False,  True, False, False,  True, False, False, False,
        True, False, False, False, False, False, False, False,  True,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True, False, False, False, False, False,
        True, False, False, False, False, False, False,  True, False,
       False, False, False, False, False])

In [75]:
sum(np_array == 1)

9

There are 9 1's in the list